(ns rooij.module.box2d.util
  (:refer-clojure :exclude [Box])
  (:require
   ["planck-js" :as planck]))

(def internal (.-internal planck))
(def Serializer (.-Serializer planck))
(def Math (.-Math planck))
(def Vec2 (.-Vec2 planck))
(def Vec3 (.-Vec3 planck))
(def Mat22 (.-Mat22 planck))
(def Mat33 (.-Mat33 planck))
(def Transform (.-Transform planck))
(def Rot (.-Rot planck))
(def AABB (.-AABB planck))
(def Shape (.-Shape planck))
(def Fixture (.-Fixture planck))
(def Body (.-Body planck))

(def Contact (.-Contact planck))
(def Joint (.-Joint planck))
(def World (.-World planck))
(def Circle (.-Circle planck))
(def Edge (.-Edge planck))
(def Polygon (.-Polygon planck))
(def Chain (.-Chain planck))
(def Box (.-Box planck))
(def DistanceJoint (.-DistanceJoint planck))
(def FrictionJoint (.-FrictionJoint planck))
(def GearJoint (.-GearJoint planck))
(def MotorJoint (.-MotorJoint planck))
(def MouseJoint (.-MouseJoint planck))
(def PrismaticJoint (.-PrismaticJoint planck))
(def PulleyJoint (.-PulleyJoint planck))
(def RevoluteJoint (.-RevoluteJoint planck))
(def RopeJoint (.-RopeJoint planck))
(def WeldJoint (.-WeldJoint planck))
(def WheelJoint (.-WheelJoint planck))
